"""Increases password length

Revision ID: 85538b314318
Revises: 7d57112c083e
Create Date: 2025-03-24 11:27:37.594536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85538b314318'
down_revision = '7d57112c083e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)

    # ### end Alembic commands ###
